apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd
  namespace: argocd
spec:
  destinations:
    - name: in-cluster
      namespace: argocd
  sourceRepos:
    - https://github.com/ymedlop/playing-with-argo-self-config.git
    - https://github.com/ymedlop/playing-with-argo-k8s-definitions.git
