apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
 name: auth
 namespace: argocd
spec:
  destinations:
    - name: docker-desktop
      namespace: auth
      server: https://kubernetes.docker.internal:6443
  sourceRepos:
    - https://github.com/ymedlop-cloud/k8s-definitions.git