apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: k8s-definitions
  namespace: argocd
spec:
  destinations:
    - name: in-cluster
      namespace: "*"
  sourceRepos:
    - https://github.com/ymedlop/playing-with-argo-k8s-definitions.git
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
