apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: argocd-gateway
spec:
  selector:
    istio: ingress
  servers:
    - hosts:
        - argo.docker-desktop.com
      port:
        name: https
        number: 443
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: argo-cert
    - hosts:
        - argo.docker-desktop.com
      port:
        name: http
        number: 80
        protocol: HTTP
      tls:
        httpsRedirect: true