apiVersion: v1
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: k8s-definitions-repo
  namespace: argocd
type: Opaque
stringData:
  project: k8s-definitions
  type: git
  url: https://github.com/ymedlop/playing-with-argo-k8s-definitions.git
