kind: Secret
apiVersion: v1
metadata:
  name: traefik-helm-repo
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  insecure: "true"
  name: traefik-helm-secret-repo
  type: helm
  url: https://helm.traefik.io/traefik
type: Opaque
