apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-self-config
spec:
  destination:
    namespace: argocd
    name: in-cluster
  project: argocd
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: ./
    repoURL: https://github.com/ymedlop/playing-with-argo-self-config.git
    targetRevision: docker-desktop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true