apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: docker-desktop
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/ymedlop/playing-with-argo-k8s-definitions.git
        revision: docker-desktop
        directories:
        - path: "docker-desktop/*"
  template:
    metadata:
      name: "{{path.basename}}"
    spec:
      project: k8s-definitions
      source:
        repoURL: https://github.com/ymedlop/playing-with-argo-k8s-definitions.git
        targetRevision: docker-desktop
        path: "{{path}}"
        helm:
          releaseName: "{{path.basename}}"
          valueFiles:
            - values.yaml
      destination:
        name: in-cluster
        namespace: "{{path.basename}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
