apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: docker-desktop
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.docker.internal:6443
  project: argocd
  source:
    path: ./apps
    repoURL: https://github.com/ymedlop/playing-with-argo-k8s-definitions.git
    targetRevision: docker-desktop
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
